- .gitmodules
- README.md
> Add instructions for cloning submodules

- pkg/ast2400/gpio_reg.go
> Fix ineffassign issues

- cmd/uinit/gpio_lib_test.go
- cmd/uinit/ncsi.go
> Fix vet issues

- .circleci/config.yml
> circleci: Skip uinit command because it fails to build for now

- Makefile
Also fixes a bug in image generation introduced in the previous pull request.
> make the makefile more makethonic

- .gitignore
- Makefile
> Do not write the Makefile target on failure

- pkg/bmc/gpio.go
- pkg/bmc/gpio_lib.go
- pkg/bmc/grpc.go
- pkg/bmc/system.go
- platform/quanta-f06-leopard-ddr3.dts
- platform/quanta-f06-leopard-ddr3/cmd/uinit/platform.go
Upstreaming latest batch of commits
> Less Fatalf, fix PWM

- .circleci/config.yml
- pkg/bmc/ssh_keys.sh
Signed-off-by: Ryan O'Leary <ryanoleary@google.com>
> circleci: Remove vendor check

- README.md
Signed-off-by: Matt Layher <mdlayher@gmail.com>
> README: recommend installing dtc and qemu-system-arm

- pkg/bmc/ncsi.go
- Returns errors throughout where the netlink.AttributeDecoder type is used.
- Uses switch statements as appropriate to reduce if/else duplication.
- Uses stdlib net to retrieve interface information as only the interface index is needed.
- Makes use of unix.NCSI_* constants which will be added when
https://go-review.googlesource.com/c/sys/+/138375 is merged.
Signed-off-by: Matt Layher <mdlayher@gmail.com>
---
Hello!  I discovered this repository this morning and wanted to pitch in a bit with the netlink portions!  TIL about NCSI and the fact that there's a generic netlink family to interact with it.  Would love to see this split out into a reusable package at some point.
For now, I've made some changes to simplify a few things, and to ensure that any potential attribute handling errors …
> pkg/bmc: clean up and add error handling in NCSI netlink interactions

- integration/testdata/boot/uinit/test.go
- pkg/bmc/grpc.go
- pkg/bmc/system.go
- pkg/bmc/ttime/roughtime.go
- pkg/roughtime/LICENSE
- pkg/roughtime/README.md
- pkg/roughtime/client.go
- pkg/roughtime/upstream/LICENSE
- pkg/roughtime/upstream/README.md
- pkg/roughtime/upstream/config/config.go
- pkg/roughtime/upstream/protocol/protocol.go
- pkg/roughtime/upstream/protocol/protocol_test.go
See comment in config/config.go how this is meant to work, but
essentially use roughtime as an authenticated time source and NTP to
tune the results of roughtime.
Fixes #4.
> Set RTC using roughtime and NTP

- .circleci/config.yml
- .gitmodules
- README.md
- config/Makefile
> Add image build step to CircleCI

- linux-patches/01-net-ncsi-Add-NCSI-Mellanox-OEM-command.diff
- linux-patches/02-mac-for-cx3.diff
- linux.config
> Correct the previous sync

- pkg/bmc/endian_little.go
- pkg/bmc/gpio_linux.go
- pkg/bmc/gpio_linux_test.go
- pkg/bmc/grpc_test.go
- pkg/bmc/interface.go
- pkg/bmc/rdnss.go
- pkg/bmc/rdnss_test.go
- pkg/bmc/system.go
> [WIP] Add support for RDNSS

- Gopkg.lock
- Gopkg.toml
- cmd/login/main.go
- pkg/bmc/system.go
- platform/quanta-f06-leopard-ddr3/cmd/uinit/main.go
- u-bmc.go
- vendor/golang.org/x/crypto/ssh/terminal/terminal.go
- vendor/golang.org/x/crypto/ssh/terminal/util.go
- vendor/golang.org/x/crypto/ssh/terminal/util_aix.go
- vendor/golang.org/x/crypto/ssh/terminal/util_bsd.go
- vendor/golang.org/x/crypto/ssh/terminal/util_linux.go
- vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go
- vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go
- vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
Right now it's pretty useless but it serves as a placeholder for any
local console authentication that will be added later.
> login: Add login cmdlet

- integration/integration_test.go
> integration: Fix qmp test

- integration/testcmd/acme/uinit/test.go
> integration: disable NTP in acme

- README.md
> ovmf: Fix command ordering

- config/config.go
- config/config_test.go
- integration/acme_test.go
- integration/testcmd/acme/uinit/test.go
- pkg/bmc/cert/load.go
- pkg/bmc/cert/load_test.go
- pkg/bmc/dns.go
- pkg/bmc/grpc.go
- pkg/bmc/interface.go
- pkg/bmc/system.go
DNS skeleton and solver interface
> acme: DNS01 solver skeleton

- Gopkg.lock
- Makefile
- integration/testcmd/acme/uinit/test.go
- integration/utils/acme.go
- pkg/bmc/dns.go
- pkg/bmc/interface.go
- pkg/bmc/system.go
Implement basic DNS server to be able to solve DNS-01 challenges.
Fixes #158
> dns: implement

- Gopkg.lock
- pkg/bmc/system.go
- vendor/github.com/u-root/u-root/pkg/rtc/rtc_linux.go
Set and use hwclock RTC when booting
Fixes #86
> rtc: implement

- README.md
> Update supported boards in README

- README.md
> readme: Add Poleg BMC as planned board

- pkg/bmc/gpio.go
- pkg/bmc/gpio_fake.go
- platform/quanta-f06-leopard-ddr3/pkg/platform/platform.go
- platform/quanta-f06-leopard-ddr3/pkg/platform/platform_test.go
This improves upon and replaces https://github.com/u-root/u-bmc/pull/177
> Support empty Buttons map

- qemu-leopard.patch
Bring the Leopard patch up to date with current OpenBMC QEMU
> qemu: Rebase patch

- Makefile
This makes the image generation a bit more readable by dropping the use
of perl and building on dd only. Additionally a new variable ROM_SIZE is
introduced to be able to set the final flash image size for e.g.
flashrom usage. This variable can be set in the platform specific
Makefile.inc.
Signed-off-by: Michael Niewöhner <foss@mniewoehner.de>
> rework image generation

- Makefile
> Makefile: use $(MAKE) also for `boot/boot.bin`

- .circleci/config.yml
- integration/utils/acme.go
- pkg/bmc/cert/load_test.go
- qemu-leopard.patch
Signed-off-by: Christian Walter <christian.walter@9elements.com>
> Fix CircleCI

- pkg/bmc/interface.go
Signed-off-by: Christian Walter <christian.walter@9elements.com>
> pkg/bmc/interface: change to changed IfUp call

- integration/integration_test.go
- u-bmc.go
Signed-off-by: Christian Walter <christian.walter@9elements.com>
> u-bmc.go: Fix Change in DefaultRamfs

- Taskfile.yml
- taskfiles/Platform.yml
Created Platform.yml to allow future platforms to build a different build chain more easily
> Taskfile modularize
